on: 
  pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests in kscript project
    steps:
    - name: Checkout the project into the container
      uses: actions/checkout@v2.3.4
    - name: GitHub Action for Build
      uses: buildtool/build-action@v1.1
      with:
        args: '--build-args KSCRIPT_VERSION=3.0.1'
    - name: Run testing script to generate mock IDEA project and run gradle test
      id: hello
      uses: plusmobileapps/kscript-action@v1.1-dev01
      with:
        kts-file: 'star-wars-char-enum.kts'