on: [push]

jobs:
  docker-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run kscript tests  
      uses: docker://plusmobileapps/kscript-action:v0.8
      with:
        entrypoint: /
      run: kscript /ktest.kts /github/workspace/star-wars-char-enum.kts
      