on: [push]

jobs:
  docker-example:
    runs-on: ubuntu-latest
    container:
      image: plusmobileapps/kscript-action:v0.8
    steps:
    - uses: actions/checkout@v2
    - name: Run kscript tests  
      run: kscript /ktest.kts /github/workspace/star-wars-char-enum.kts
      