on: 
  pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests in kscript project
    steps:
    - name: Checkout the project into the container
      uses: actions/checkout@v2.3.4
    - name: Run testing script to generate mock IDEA project and run gradle test
      id: hello
      uses: plusmobileapps/kscript-action@v1.2-dev03
      with:
        kts-file: 'star-wars-char-enum.kts'
        kscript-version: '3.0.2'
        kotlin-version: '1.4.21'
        fail-on-failure: 'false'
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**/test-results/test/TEST-*.xml'
        fail_on_failure: 'true'
        require_tests: 'true'
